export const userArr = [
  {
    email: "studenttest@gmail.com",
    password: "qwerty",
    username: "studenttest",
    fullName: "studenttest",
    usertype: "student",
  },
  {
    email: "studenttest1@gmail.com",
    password: "qwerty",
    username: "studenttest1",
    fullName: "studenttest1",
    usertype: "student",
  },
  {
    email: "studenttest2@gmail.com",
    password: "qwerty",
    username: "studenttest2",
    fullName: "studenttest2",
    usertype: "student",
  },
  {
    email: "studenttest3@gmail.com",
    password: "qwerty",
    username: "studenttest3",
    fullName: "studenttest3",
    usertype: "student",
  },
  {
    email: "studenttest4@gmail.com",
    password: "qwerty",
    username: "studenttest4",
    fullName: "studenttest4",
    usertype: "student",
  },
  {
    email: "teachertest@gmail.com",
    password: "qwerty",
    username: "teachertest",
    fullName: "teachertest",
    usertype: "teacher",
  },
  {
    email: "teachertest2@gmail.com",
    password: "qwerty",
    username: "teachertest2",
    fullName: "teachertest2",
    usertype: "teacher",
  },
  {
    email: "teachertest3@gmail.com",
    password: "qwerty",
    username: "teachertest3",
    fullName: "teachertest3",
    usertype: "teacher",
  },
];
