export const userArr = [
  {
    email: "studenttest@gmail.com",
    password: "ooo",
    username: "studenttest",
    fullname: "michael whalen",
    usertype: "student",
  },
  {
    email: "studenttest1@gmail.com",
    password: "ooo",
    username: "studenttest1",
    fullname: "studenttest1",
    usertype: "student",
  },
  {
    email: "studenttest2@gmail.com",
    password: "ooo",
    username: "studenttest2",
    fullname: "studenttest2",
    usertype: "student",
  },
  {
    email: "studenttest3@gmail.com",
    password: "ooo",
    username: "studenttest3",
    fullname: "studenttest3",
    usertype: "student",
  },
  {
    email: "studenttest4@gmail.com",
    password: "ooo",
    username: "studenttest4",
    fullname: "studenttest4",
    usertype: "student",
  },
  {
    email: "teachertest@gmail.com",
    password: "ooo",
    username: "teachertest",
    fullname: "teachertest",
    usertype: "teacher",
  },
  {
    email: "teachertest2@gmail.com",
    password: "ooo",
    username: "teachertest2",
    fullname: "teachertest2",
    usertype: "teacher",
  },
  {
    email: "teachertest3@gmail.com",
    password: "ooo",
    username: "teachertest3",
    fullname: "teachertest3",
    usertype: "teacher",
  },
];
