name: 🔥 New Feature
description: Add a new feature to Regents Prep
labels: ["enhancement"]
title: "feature: "
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what you want to do.
      placeholder: I want to add yoda to the bottom of every scrollable container in the app (for the funny) (it wont interfere with normal usage of the app probably)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested solution
      description: Describe your technical solution to the problem.
      placeholder: At the bottom of every scrollable container, we can add yoda with `mt-20` to make sure it stays at the bottom. We can also use the `IntersectionObserver` JavaScript API to detect when the user scrolls past the normal scrollable distance of the container, and automatically force the scrollable view back up when the user stops scrolling
    validations:
      required: true

  - type: textarea
    attributes:
      label: Rationale
      description: Why should this be added?
      placeholder: It would be funny

  - type: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't [already an issue](https://github.com/sitechtimes/regents-prep-app-frontend/issues) that suggests the same feature to avoid creating a duplicate.
          required: true
