name: 🔥 New Feature
description: Add a new feature to Regents Prep
labels: ["enhancement"]
title: "feature: "
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what you want to do.
      placeholder: I want to add yoda to every page (for the funny)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested solution
      description: Describe your solution to the problem.
      placeholder: We can add a yoda to the bottom of every scrollable container so it wont interfere with normal usage of the app probably
    validations:
      required: true

  - type: textarea
    attributes:
      label: Rationale
      description: Why should this be added?
      placeholder: It would be funny

  - type: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't [already an issue](https://github.com/sitechtimes/regents-prep-app-frontend/issues) that reports the same bug to avoid creating a duplicate.
          required: true
